plot(Data)
plot(Data$Pre)
plot(Data$Pre, type = 'p')
plot(Data$Pre, type = 'p' , col='red')
plot(Data$Pre, type = 'p', col='red', main = 'Graph', xlab='Data' , ylab = 'frequency')
plot(density(Data$Pre), main = 'Density-Graph', xlab = 'Data', col='red' ,lwd =3, xlim=c(2,7))
lines(density(Data$Post), col='blue', lwd=3)
legend('topleft', c('Post','Pre'),fill = c('blue','red'))
legend('topright', c('Post','Pre'),fill = c('blue','red'))
legend('bottom', c('Post','Pre'),fill = c('blue','red'))
